"""
Flattening the board state loses too much structural information, so better is to use CNN.
CNN can take (2+n)-dimentional tensor (2-d matrix of board size with n channels)
Channels filled with 0/1:
 - whose turn (all 0s or 1s)
 - LIGHT MAN
 - LIGHT KING
 - DARK MAN
 - DARK KING

One approach is to input to the network list of possible moves in the state and then network 
selects from this. But this requires variational number of inputs and variational number of outputs.
Also in what form this would be inserted and outputed is not trivial.

Easier approach is for network to have constant output size where size will be the number of 
all possible actions. Then not possible moves will be filtered (masked) using possible moves 
generated by the engine. Network outputs probability distribution over all possible moves.

How to generate space of all possible moves in checkers? How to manage multi-positional moves?
If considered all possible multi-positional moves the moves space would be gigantical. So only 
starting and ending position possibilities will be generated as the available to be choosen. 
From one position to the other there are many possible paths.Model outputs probability for 
each start, end position pair. If the most probable output matches more than one move that are
generated by the engine it means that paths are equal in terms of capture maximalization so it is
less relevant which one  will be selected.

UCB (Upper Confidence Bounds) selects from nodes already added to the MCTS tree by using
wins and visits stats.

Policy network will tell which moves to take during simulation step in MCTS process.

Value network evaluates the position on the board when the game is not ended.
Without value network simulation step in the MCTS process has to get to the final
node to be able to tell what value to backpropagate. With properly pretrained value network
depth of the simulation step can be reduced. It is crucial because we can tell position 
looks 'bad' or 'good' by using intuition from the previously played games.
Then more iterations (full mcts processes) can be run in the same amount of time.
So we get more expanded tree.

Limit for the simulation depth can be hardcoded or every few steps in the simulation
value network can be called and if it is sure (for example 0.7 for dark and 0.3 for light)
then simulation can be ended.

How to handle delayed rewards (which appear in checkers)?
In checkers there is only one reward signal which is the final outcome.
There are known methods to handle delayed rewards such as:
 - value functions (estimated as value networks), which estimate the expected
    long-term reward for taking an action in a given state
 - Temporal-Difference (TD) learning, which uses mix of immediate rewards and
    predictions of future rewards
 - policy gradient methods, which optimize the policy directly
    by adjusting action probabilities based on the estimated long-term reward
 - algorithms like Advantage Actor-Critic (A2C) combine policy gradients with a value 
    function (the “critic”) to provide immediate feedback on action quality

Loss function used in the AlphaZero:
    L = (V - Z)^2 - T*log(P) + c||O||^2
    where:
    - Value Loss (MSE):  (V - Z)^2
    - Policy Loss (Cross Entropy): T*log(P)
    - Regularization: c||O||^2
    where:
    - T - distribution of visits count obtained by running MCTS - target for policy network
    - P - propability disctribution outputed by the policy network
    - Z - final outcome of the game - target for value network
    - V - estimate outputed by the value network
    - O - weights of the model
    - c - hiperparameter

"""
from queue import Empty
import torch.multiprocessing as mp
from pathlib import Path
import numpy as np
import torch
import copy
from copy import deepcopy
from tqdm import tqdm
from ai.ai.test import test
from ai.engine.game import Game, Outcome
from ai.ai.policy_network import PolicyNetwork
from ai.ai.value_network import ValueNetwork
from ai.ai.plot import Plot
from ai.ai.neural_mcts import MCTSNodeNN1, MCTSNodeNN2
from ai.ai.download import download_model
from ai.ai.workers import self_play_worker


if __name__ == "__main__":
    # on which type of algorithm you want to train both policy and value network
    TYPE = 2

    if TYPE == 1:
        LEARNING_RATE = 0.0001
        N_EPOCHS = 100 # one epoch is full game
        N_SIMULATIONS = 50
        N_EPOCH_TEST = 25

        value_loss_plot = Plot("Average Value Network Loss per Episode", "Episode", "Average Loss")
        policy_loss_plot = Plot("Average Policy Network Loss per Episode", "Episode", "Average Loss")
        win_rate_plot = Plot("Win Rate in 10 games", f"Test Number (Every {N_EPOCH_TEST} Epoch)", "Win Rate")

        game = Game()
        moves_space = game.possible_moves_space()
        policy_model = PolicyNetwork(5, len(moves_space))
        value_model = ValueNetwork(5)
        # weight decay adds penalty for bigger weights
        policy_optimizer = torch.optim.Adam(policy_model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
        value_optimizer = torch.optim.Adam(value_model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)


        BASE_DIR = Path(__file__).resolve().parent
        POLICY_PATH = BASE_DIR.parent / "models" / "1.0"
        POLICY_PATH.mkdir(parents=True, exist_ok=True)
        POLICY_MODEL_NAME = "PolicyNetwork.pt"
        VALUE_PATH = BASE_DIR.parent / "models" / "1.0"
        VALUE_PATH.mkdir(parents=True, exist_ok=True)
        VALUE_MODEL_NAME = "ValueNetwork.pt"
        # uncomment when continue learning pre-trained models
        # retrieving policy network
        POLICY_MODEL_URL = "https://drive.google.com/file/d/1RSN43tz27N9WY8mZAJqioTh2WA1fbslM/view?usp=sharing"
        if not (POLICY_PATH / POLICY_MODEL_NAME).exists():
            download_model(POLICY_MODEL_URL, str(POLICY_PATH / POLICY_MODEL_NAME))
        checkpoint = torch.load(POLICY_PATH / POLICY_MODEL_NAME)
        policy_model.load_state_dict(checkpoint["model"])
        policy_optimizer.load_state_dict(checkpoint["optimizer"])

        # retrieving value network
        VALUE_MODEL_URL = "https://drive.google.com/file/d/1nRVQ64_sWxXUj6QQLYEVKfFZOtucvdkm/view?usp=sharing"
        if not (VALUE_PATH / VALUE_MODEL_NAME).exists():
            download_model(VALUE_MODEL_URL, str(VALUE_PATH / VALUE_MODEL_NAME))
        checkpoint = torch.load(VALUE_PATH / VALUE_MODEL_NAME)
        value_model.load_state_dict(checkpoint["model"])
        value_optimizer.load_state_dict(checkpoint["optimizer"])

        mean_squared_error_loss_fn = torch.nn.MSELoss()

        try:
            for epoch in tqdm(range(N_EPOCHS)):
                game = Game()
                history = []

                count = 0
                # self playing part
                while game.is_in_progress():
                    count += 1
                    print(f"Move: {count}   ", end="\r", flush=True)
                    root = MCTSNodeNN1(game, policy_model, value_model, game.whose_turn)

                    for _ in range(N_SIMULATIONS):
                        node = root
                        while not node.is_terminal() and node.is_fully_expanded():
                            node = node.best_child()

                        if not node.is_terminal() and not node.is_fully_expanded():
                            node = node.expand()

                        outcome = node.rollout()
                        node.backpropagate(outcome)

                    moves_space = game.possible_moves_space()
                    pi = np.zeros(len(moves_space), dtype=np.float32)
                    for child in root.children:
                        action = child.action

                        for i, (start, end) in enumerate(moves_space):
                            if action in game.moves_from(start, end):
                                pi[i] = child.visits

                    if pi.sum() > 0:
                        pi /= pi.sum()
                    else:
                        mask = np.array(game.possible_moves_mask(), dtype=np.float32)
                        pi = mask / mask.sum()
                    history.append((deepcopy(game), pi))
                    rng = np.random.default_rng()
                    action_idx = rng.choice(np.arange(len(moves_space)), p=pi)
                    start_end = moves_space[action_idx]
                    moves = game.moves_from(start_end[0], start_end[1])
                    game.make_move(moves[0])

                outcome = game.final_outcome()
                if outcome == Outcome.LIGHT:
                    z = [1,0]
                elif outcome == Outcome.DARK:
                    z = [0,1]
                else:
                    z = [0.5,0.5]

                loss = 0.0

                value_loss_stats = []
                policy_loss_stats = []
                for (s, t) in history:
                    action_probability_dist = policy_model(torch.from_numpy(np.array(s.get_state_list())).unsqueeze(0).float())[0]
                    mask = torch.tensor(s.possible_moves_mask(), dtype=torch.float32)
                    action_probability_dist = action_probability_dist * mask
                    action_probability_dist = action_probability_dist / action_probability_dist.sum()
                    action_target = torch.tensor(t, dtype=torch.float32)
                    action_target = action_target / torch.sum(action_target)
                    log_probs = torch.log(action_probability_dist + 1e-8)

                    ce_loss = -torch.sum(action_target * log_probs)
                    policy_loss_stats.append(ce_loss.detach().numpy())

                    evaluation_probability_dist = value_model(torch.from_numpy(np.array(s.get_state_list())).unsqueeze(0).float())[0]
                    target_value = z[0]-z[1]
                    target_tensor = torch.tensor(target_value, dtype=torch.float32)
                    mse_loss = mean_squared_error_loss_fn((evaluation_probability_dist[0]-evaluation_probability_dist[1]), target_tensor)
                    value_loss_stats.append(mse_loss.detach().numpy())
                    loss = loss + ce_loss + mse_loss

                policy_optimizer.zero_grad()
                value_optimizer.zero_grad()
                loss.backward()
                value_optimizer.step()
                policy_optimizer.step()

                value_loss_plot.update(sum(value_loss_stats) / len(value_loss_stats))
                policy_loss_plot.update(sum(policy_loss_stats) / len(policy_loss_stats))

                # Model created using pytorch has learnable parameters (weights and biases)
                # which are instances of torch.nn.parameter.Parameter which is Tensor subclass
                # During forward pass computational graph is build where every operation creates
                # node in this graph and each node stores the operation performed and reference to the
                # previous tensors.
                # Calling .backward() triggers reverse-mode automatic differentiation (backpropagation)
                # which computes partial derivatives for each node using the chain rule through the graph.
                # Gradients are accumulated into .grad fields of leaf
                # tensors (leaf tensors are input tensors).
                # The grad is the gradient of the loss with respect to the tensor we are probing.
                # Before running backward(), this attribute is set to None.
                # Optimizer has reference to the leaf tensors because they were passed to its constructor.

                if epoch % N_EPOCH_TEST == 0:
                    print("Starting Test")
                    #win_rate_plot.update(test(policy_model, value_model)) # it heavily extends learning time

        finally:
            (BASE_DIR.parent / "models").mkdir(exist_ok=True)
            torch.save(
                {"model": policy_model.state_dict(), "optimizer": policy_optimizer.state_dict()},
                BASE_DIR.parent / "models" / POLICY_MODEL_NAME)
            torch.save(
                {"model": value_model.state_dict(), "optimizer": value_optimizer.state_dict()},
                BASE_DIR.parent / "models" / VALUE_MODEL_NAME)
            PLOT_DIR = BASE_DIR.parent / "plots"
            PLOT_DIR.mkdir(exist_ok=True)
            value_loss_plot.save(str(PLOT_DIR / "value_average_loss.png"))
            policy_loss_plot.save(str(PLOT_DIR / "policy_average_loss.png"))
            win_rate_plot.save(str(PLOT_DIR / "win_rate.png"))

    elif TYPE == 2: # -----------------------------------------------------------------------------------------------------------------------------------------
        LEARNING_RATE = 0.0001
        N_EPOCHS = 100
        N_EPOCH_TEST = 25

        value_loss_plot = Plot("Average Value Network Loss per Episode", "Episode", "Average Loss")
        policy_loss_plot = Plot("Average Policy Network Loss per Episode", "Episode", "Average Loss")
        win_rate_plot = Plot("Win Rate in 10 games against Classic MCTS", f"Test Number (Every {N_EPOCH_TEST} Epoch)", "Win Rate")

        game = Game()
        moves_space = game.possible_moves_space()
        policy_model = PolicyNetwork(5, len(moves_space))
        value_model = ValueNetwork(5)
        # weight decay adds penalty for bigger weights
        policy_optimizer = torch.optim.Adam(policy_model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
        value_optimizer = torch.optim.Adam(value_model.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)


        BASE_DIR = Path(__file__).resolve().parent
        POLICY_PATH = BASE_DIR.parent / "models" / "2.1"
        POLICY_PATH.mkdir(parents=True, exist_ok=True)
        POLICY_MODEL_NAME = "PolicyNetwork.pt"
        VALUE_PATH = BASE_DIR.parent / "models" / "2.1"
        VALUE_PATH.mkdir(parents=True, exist_ok=True)
        VALUE_MODEL_NAME = "ValueNetwork.pt"

        #uncomment when continue learning pre-trained models
        # retrieving policy network
        # POLICY_MODEL_URL = "https://drive.google.com/file/d/1BHl0o2WcBZ_NWZf2LHr0ZAmzTzUoENRP/view?usp=sharing" # 2.0
        POLICY_MODEL_URL = "https://drive.google.com/file/d/17YeKaLuj_j3I8kx41n3CWCHxOB5InDsO/view?usp=sharing" # 2.1
        if not (POLICY_PATH / POLICY_MODEL_NAME).exists():
            download_model(POLICY_MODEL_URL, str(POLICY_PATH / POLICY_MODEL_NAME))
        checkpoint = torch.load(POLICY_PATH / POLICY_MODEL_NAME)
        policy_model.load_state_dict(checkpoint["model"])
        policy_optimizer.load_state_dict(checkpoint["optimizer"])

        # retrieving value network
        # VALUE_MODEL_URL = "https://drive.google.com/file/d/1_d-Ra5BSBj5PXtlrqyB_Bqlexv1gPCRm/view?usp=sharing" # 2.0
        VALUE_MODEL_URL = "https://drive.google.com/file/d/1spqhvWi8pIQ2xYO_5CBGPE11p94EYBcI/view?usp=sharing" # 2.1
        if not (VALUE_PATH / VALUE_MODEL_NAME).exists():
            download_model(VALUE_MODEL_URL, str(VALUE_PATH / VALUE_MODEL_NAME))
        checkpoint = torch.load(VALUE_PATH / VALUE_MODEL_NAME)
        value_model.load_state_dict(checkpoint["model"])
        value_optimizer.load_state_dict(checkpoint["optimizer"])

        try:
            for epoch in tqdm(range(N_EPOCHS), desc="Training"):
                # parallel self-play
                policy_state_clean = copy.deepcopy({k: v.cpu() for k, v in policy_model.state_dict().items()})
                value_state_clean = copy.deepcopy({k: v.cpu() for k, v in value_model.state_dict().items()})
                ctx = mp.get_context('spawn')
                min_n_workers = 4
                n_workers = min(min_n_workers, ctx.cpu_count()-1)
                with ctx.Manager() as manager:
                    display_queue = manager.Queue()
                    # to the Pool is passed number of new processes
                    with ctx.Pool(n_workers) as pool:
                        # map_async is not stoping code execution
                        result_async = pool.map_async(
                            self_play_worker,
                            # each tuple in the list is passed as a task to the worker process
                            [(Game(), policy_state_clean, value_state_clean, False, display_queue) for _ in range(n_workers-1)] + [(Game(), policy_state_clean, value_state_clean, True, display_queue)]
                        )
                        while not result_async.ready():
                            try:
                                data = display_queue.get(timeout=1)

                                tqdm.write("\033[H\033[J", end="")
                                tqdm.write(data["title"])
                                tqdm.write(data["board"])
                                tqdm.write(data["move"])

                            except Empty:
                                pass

                        # final flush
                        try:
                            while True:
                                data = display_queue.get_nowait()

                                tqdm.write("\033[H\033[J", end="")
                                tqdm.write(data["title"])
                                tqdm.write(data["board"])
                                tqdm.write(data["move"])
                        except Empty:
                            pass
                        tqdm.write("\033[H\033[J", end="")
                        histories = result_async.get()

                total_loss = 0.0
                value_loss_stats = []
                policy_loss_stats = []
                for (history, z) in histories:
                    for i, (state_list, mask, pi_target) in enumerate(history):
                        # # early-game positions should be evaluated closer to neutral
                        GAMMA = 0.99
                        distance_to_end = len(history) - i
                        discounted_z = z * (GAMMA ** distance_to_end)
                        target_z = discounted_z

                        # target_z = z

                        state_tensor = torch.tensor(state_list, dtype=torch.float32).unsqueeze(0)
                        # POLICY
                        policy_pred = policy_model(state_tensor)[0]
                        mask = torch.tensor(mask, dtype=torch.float32)
                        policy_pred = policy_pred * mask
                        policy_pred = policy_pred / (policy_pred.sum() + 1e-8)
                        pi_target = torch.tensor(pi_target, dtype=torch.float32)
                        log_probs = torch.log(policy_pred + 1e-8)
                        policy_loss = -torch.sum(pi_target * log_probs)
                        # VALUE
                        value_pred = value_model(state_tensor)[0]
                        scalar_value = value_pred[0] - value_pred[1]
                        target_tensor = torch.tensor(target_z, dtype=torch.float32)
                        value_loss = (scalar_value - target_tensor) ** 2
                        value_loss_stats.append(value_loss.detach().numpy())
                        policy_loss_stats.append(policy_loss.detach().numpy())
                        total_loss += policy_loss + value_loss

                policy_optimizer.zero_grad()
                value_optimizer.zero_grad()
                total_loss.backward()
                policy_optimizer.step()
                value_optimizer.step()

                value_loss_plot.update(sum(value_loss_stats) / len(value_loss_stats))
                policy_loss_plot.update(sum(policy_loss_stats) / len(policy_loss_stats))

                if epoch % N_EPOCH_TEST == 0 and epoch != 0:
                    print("Starting Test")
                    win_rate_plot.update(test(policy_model, value_model)) # it heavily extends learning time
        finally:
            (BASE_DIR.parent / "models").mkdir(exist_ok=True)
            torch.save(
                {"model": policy_model.state_dict(), "optimizer": policy_optimizer.state_dict()},
                BASE_DIR.parent / "models" / POLICY_MODEL_NAME)
            torch.save(
                {"model": value_model.state_dict(), "optimizer": value_optimizer.state_dict()},
                BASE_DIR.parent / "models" / VALUE_MODEL_NAME)
            PLOT_DIR = BASE_DIR.parent / "plots"
            PLOT_DIR.mkdir(exist_ok=True)
            value_loss_plot.save(str(PLOT_DIR / "value_average_loss.png"))
            policy_loss_plot.save(str(PLOT_DIR / "policy_average_loss.png"))
            win_rate_plot.save(str(PLOT_DIR / "win_rate.png"))
